Add case study on phase retrieval in Stan
stan-dev/stan-dev.github.io pull request #169
Opened 2022-07-01 14:00 UTC by WardBrian

This adds a new case study on performing Fourier image reconstruction in Stan, specifically for holographic coherent diffraction imaging (HCDI). 

It is based on the forward model in Barmherzig and Sun 2022: https://opg.optica.org/oe/fulltext.cfm?uri=oe-30-5-6886&id=469550

A rendered version can be seen here: https://brianward.dev/holoml-in-stan/HoloML%20in%20Stan.html

This relies on features in Stan 2.30

2022-07-01 16:37 UTC, bob-carpenter requested changes
This looks really great. 

We need to cite the image---it comes from Wikipedia and has a CC attribution license.  here's how Wikipedia attributes it, and we should just follow them verbatim---there's a "use this file on the web link":

https://commons.wikimedia.org/wiki/File:Electron_microscopic_image_of_a_mimivirus_-_journal.ppat.1000087.g007_crop.png

> Ghigo E, Kartenbeck J, Lien P, Pelkmans L, Capo C, Mege JL, Raoult D., CC BY 2.5 <https://creativecommons.org/licenses/by/2.5>, via Wikimedia Commons

[optional] On re-reading, the only thing I found a bit confusing is the discussion of expected number of photons because we have the experimental total number of photons which gives expected photons per sensor, but then we have the image which through the forward model gives us a more fine-grained per-sensor expectation (that's the Poisson rate parameter).  There's not a standard way to talk about this, so I'm OK leaving as is.

2022-07-01 16:37 UTC, bob-carpenter commented on users/documentation/case-studies.md
> ->>>>>>> origin/master
[comment]
Thanks for fixing.

2022-07-01 17:32 UTC, WardBrian commented
I added the attribution wikipedia recommends

2022-07-02 21:48 UTC, bob-carpenter approved these changes

2022-07-02 21:49 UTC, merged